### ISSUE TITLE
System->Inputs page is unaccessible

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#1000]
Hi,

Clean install of graylog2-0.93.0-SNAPSHOT-20141209180626 + graylog2-web-interface-0.93.0-SNAPSHOT-20141209174205.

Accessing System->Inputs gives an error:
```
# [error] o.g.r.l.ApiClient - API failed due to IO error
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: {"types":{"org.graylog2.inputs.gelf.http.GELFHttpInput":{"name":"GELF HTTP","requested_configuration":{"port":{"additional_info":{},"default_value":12201,"description":"Port to listen on.","human_name":"Port","is_optional":false,"attributes":["is_port_number"],"type":"number"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"bind_address":{"additional_info":{},"default_value":"0.0.0.0","description":"Address to listen on. For example 0.0.0.0 or 127.0.0.1.","human_name":"Bind address","is_optional":false,"attributes":[],"type":"text"},"recv_buffer_size":{"additional_info":{},"default_value":1048576,"description":"The size in bytes of the recvBufferSize for network connections to this input.","human_name":"Receive Buffer Size","is_optional":true,"attributes":["only_positive"],"type":"number"},"enable_cors":{"additional_info":{},"default_value":true,"description":"Input sends CORS headers to satisfy browser security policies","human_name":"Enable CORS","is_optional":true,"attributes":[],"type":"boolean"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.gelf.udp.GELFUDPInput":{"name":"GELF UDP","requested_configuration":{"port":{"additional_info":{},"default_value":12201,"description":"Port to listen on.","human_name":"Port","is_optional":false,"attributes":["is_port_number"],"type":"number"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"bind_address":{"additional_info":{},"default_value":"0.0.0.0","description":"Address to listen on. For example 0.0.0.0 or 127.0.0.1.","human_name":"Bind address","is_optional":false,"attributes":[],"type":"text"},"recv_buffer_size":{"additional_info":{},"default_value":1048576,"description":"The size in bytes of the recvBufferSize for network connections to this input.","human_name":"Receive Buffer Size","is_optional":true,"attributes":["only_positive"],"type":"number"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.syslog.tcp.SyslogTCPInput":{"name":"Syslog TCP","requested_configuration":{"port":{"additional_info":{},"default_value":514,"description":"Port to listen on.","human_name":"Port","is_optional":false,"attributes":["is_port_number"],"type":"number"},"expand_structured_data":{"additional_info":{},"default_value":false,"description":"Expand structured data elements by prefixing attributes with their SD-ID?","human_name":"Expand structured data?","is_optional":true,"attributes":[],"type":"boolean"},"allow_override_date":{"additional_info":{},"default_value":true,"description":"Allow to override with current date if date could not be parsed?","human_name":"Allow overriding date?","is_optional":true,"attributes":[],"type":"boolean"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"bind_address":{"additional_info":{},"default_value":"0.0.0.0","description":"Address to listen on. For example 0.0.0.0 or 127.0.0.1.","human_name":"Bind address","is_optional":false,"attributes":[],"type":"text"},"store_full_message":{"additional_info":{},"default_value":false,"description":"Store the full original syslog message as full_message?","human_name":"Store full message?","is_optional":true,"attributes":[],"type":"boolean"},"use_null_delimiter":{"additional_info":{},"default_value":false,"description":"Use null byte as frame delimiter? Default is newline.","human_name":"Null frame delimiter?","is_optional":true,"attributes":[],"type":"boolean"},"recv_buffer_size":{"additional_info":{},"default_value":1048576,"description":"The size in bytes of the recvBufferSize for network connections to this input.","human_name":"Receive Buffer Size","is_optional":true,"attributes":["only_positive"],"type":"number"},"force_rdns":{"additional_info":{},"default_value":false,"description":"Force rDNS resolution of hostname? Use if hostname cannot be parsed.","human_name":"Force rDNS?","is_optional":true,"attributes":[],"type":"boolean"},"max_message_size":{"additional_info":{},"default_value":2097152,"description":"The maximum length of a message.","human_name":"Maximum message size","is_optional":true,"attributes":["only_positive"],"type":"number"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.kafka.KafkaInput":{"name":"Kafka Input","requested_configuration":{"fetch_wait_max":{"additional_info":{},"default_value":100,"description":"Wait for this time or the configured minimum size of a message batch before fetching.","human_name":"Fetch maximum wait time (ms)","is_optional":false,"attributes":[],"type":"number"},"topic_filter":{"additional_info":{},"default_value":"^your-topic$","description":"Every topic that matches this regular expression will be consumed.","human_name":"Topic filter regex","is_optional":false,"attributes":[],"type":"text"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"threads":{"additional_info":{},"default_value":2,"description":"Number of processor threads to spawn. Use one thread per Kafka topic partition.","human_name":"Processor threads","is_optional":false,"attributes":[],"type":"number"},"zookeeper":{"additional_info":{},"default_value":"192.168.1.1:2181","description":"Host and port of the ZooKeeper that is managing your Kafka cluster.","human_name":"ZooKeeper address","is_optional":false,"attributes":[],"type":"text"},"fetch_min_bytes":{"additional_info":{},"default_value":5,"description":"Wait for a message batch to reach at least this size or the configured maximum wait time before fetching.","human_name":"Fetch minimum bytes","is_optional":false,"attributes":[],"type":"number"}},"exclusive":false,"link_to_docs":"http://www.graylog2.org/resources/documentation/sending/kafka"},"org.graylog2.inputs.syslog.udp.SyslogUDPInput":{"name":"Syslog UDP","requested_configuration":{"port":{"additional_info":{},"default_value":514,"description":"Port to listen on.","human_name":"Port","is_optional":false,"attributes":["is_port_number"],"type":"number"},"expand_structured_data":{"additional_info":{},"default_value":false,"description":"Expand structured data elements by prefixing attributes with their SD-ID?","human_name":"Expand structured data?","is_optional":true,"attributes":[],"type":"boolean"},"allow_override_date":{"additional_info":{},"default_value":true,"description":"Allow to override with current date if date could not be parsed?","human_name":"Allow overriding date?","is_optional":true,"attributes":[],"type":"boolean"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"bind_address":{"additional_info":{},"default_value":"0.0.0.0","description":"Address to listen on. For example 0.0.0.0 or 127.0.0.1.","human_name":"Bind address","is_optional":false,"attributes":[],"type":"text"},"store_full_message":{"additional_info":{},"default_value":false,"description":"Store the full original syslog message as full_message?","human_name":"Store full message?","is_optional":true,"attributes":[],"type":"boolean"},"recv_buffer_size":{"additional_info":{},"default_value":1048576,"description":"The size in bytes of the recvBufferSize for network connections to this input.","human_name":"Receive Buffer Size","is_optional":true,"attributes":["only_positive"],"type":"number"},"force_rdns":{"additional_info":{},"default_value":false,"description":"Force rDNS resolution of hostname? Use if hostname cannot be parsed.","human_name":"Force rDNS?","is_optional":true,"attributes":[],"type":"boolean"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.radio.RadioAMQPInput":{"name":"Graylog2 Radio Input (AMQP)","requested_configuration":{"queue":{"additional_info":{},"default_value":"graylog2-radio-messages","description":"Name of queue that is created.","human_name":"Queue","is_optional":false,"attributes":[],"type":"text"},"broker_username":{"additional_info":{},"default_value":"","description":"Username to connect to AMQP broker","human_name":"Username","is_optional":true,"attributes":[],"type":"text"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"prefetch":{"additional_info":{},"default_value":100,"description":"For advanced usage: AMQP prefetch count. Default is 100.","human_name":"Prefetch count","is_optional":false,"attributes":[],"type":"number"},"broker_password":{"additional_info":{},"default_value":"","description":"Password to connect to AMQP broker","human_name":"Password","is_optional":true,"attributes":["is_password"],"type":"text"},"broker_hostname":{"additional_info":{},"default_value":"","description":"Hostname of the AMQP broker to use","human_name":"Broker hostname","is_optional":false,"attributes":[],"type":"text"},"routing_key":{"additional_info":{},"default_value":"graylog2-radio-message","description":"Routing key to listen for.","human_name":"Routing key","is_optional":false,"attributes":[],"type":"text"},"broker_vhost":{"additional_info":{},"default_value":"/","description":"Virtual host of the AMQP broker to use","human_name":"Broker virtual host","is_optional":false,"attributes":[],"type":"text"},"broker_port":{"additional_info":{},"default_value":5672,"description":"Port of the AMQP broker to use","human_name":"Broker port","is_optional":true,"attributes":["is_port_number"],"type":"number"},"parallel_queues":{"additional_info":{},"default_value":1,"description":"Number of parallel QUeues","human_name":"Number of Queues","is_optional":false,"attributes":[],"type":"number"},"exchange":{"additional_info":{},"default_value":"graylog2","description":"Name of exchange to bind to.","human_name":"Exchange","is_optional":false,"attributes":[],"type":"text"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.gelf.tcp.GELFTCPInput":{"name":"GELF TCP","requested_configuration":{"port":{"additional_info":{},"default_value":12201,"description":"Port to listen on.","human_name":"Port","is_optional":false,"attributes":["is_port_number"],"type":"number"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"bind_address":{"additional_info":{},"default_value":"0.0.0.0","description":"Address to listen on. For example 0.0.0.0 or 127.0.0.1.","human_name":"Bind address","is_optional":false,"attributes":[],"type":"text"},"use_null_delimiter":{"additional_info":{},"default_value":true,"description":"Use null byte as frame delimiter? Default is newline.","human_name":"Null frame delimiter?","is_optional":true,"attributes":[],"type":"boolean"},"recv_buffer_size":{"additional_info":{},"default_value":1048576,"description":"The size in bytes of the recvBufferSize for network connections to this input.","human_name":"Receive Buffer Size","is_optional":true,"attributes":["only_positive"],"type":"number"},"max_message_size":{"additional_info":{},"default_value":2097152,"description":"The maximum length of a message.","human_name":"Maximum message size","is_optional":true,"attributes":["only_positive"],"type":"number"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.amqp.AMQPInput":{"name":"AMQP Input","requested_configuration":{"queue":{"additional_info":{},"default_value":"log-messages","description":"Name of queue that is created.","human_name":"Queue","is_optional":false,"attributes":[],"type":"text"},"broker_username":{"additional_info":{},"default_value":"","description":"Username to connect to AMQP broker","human_name":"Username","is_optional":true,"attributes":[],"type":"text"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"prefetch":{"additional_info":{},"default_value":100,"description":"For advanced usage: AMQP prefetch count. Default is 100.","human_name":"Prefetch count","is_optional":false,"attributes":[],"type":"number"},"broker_password":{"additional_info":{},"default_value":"","description":"Password to connect to AMQP broker","human_name":"Password","is_optional":true,"attributes":["is_password"],"type":"text"},"broker_hostname":{"additional_info":{},"default_value":"","description":"Hostname of the AMQP broker to use","human_name":"Broker hostname","is_optional":false,"attributes":[],"type":"text"},"routing_key":{"additional_info":{},"default_value":"#","description":"Routing key to listen for.","human_name":"Routing key","is_optional":false,"attributes":[],"type":"text"},"broker_vhost":{"additional_info":{},"default_value":"/","description":"Virtual host of the AMQP broker to use","human_name":"Broker virtual host","is_optional":false,"attributes":[],"type":"text"},"broker_port":{"additional_info":{},"default_value":5672,"description":"Port of the AMQP broker to use","human_name":"Broker port","is_optional":true,"attributes":["is_port_number"],"type":"number"},"parallel_queues":{"additional_info":{},"default_value":1,"description":"Number of parallel QUeues","human_name":"Number of Queues","is_optional":false,"attributes":[],"type":"number"},"exchange":{"additional_info":{},"default_value":"log-messages","description":"Name of exchange to bind to.","human_name":"Exchange","is_optional":false,"attributes":[],"type":"text"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.radio.RadioKafkaInput":{"name":"Graylog2 Radio Input (Kafka)","requested_configuration":{"fetch_wait_max":{"additional_info":{},"default_value":100,"description":"Wait for this time or the configured minimum size of a message batch before fetching.","human_name":"Fetch maximum wait time (ms)","is_optional":false,"attributes":[],"type":"number"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"threads":{"additional_info":{},"default_value":2,"description":"Number of processor threads to spawn. Use one thread per Kafka topic partition.","human_name":"Processor threads","is_optional":false,"attributes":[],"type":"number"},"zookeeper":{"additional_info":{},"default_value":"192.168.1.1:2181","description":"Host and port of the ZooKeeper that is managing your Kafka cluster.","human_name":"ZooKeeper address","is_optional":false,"attributes":[],"type":"text"},"fetch_min_bytes":{"additional_info":{},"default_value":5,"description":"Wait for a message batch to reach at least this size or the configured maximum wait time before fetching.","human_name":"Fetch minimum bytes","is_optional":false,"attributes":[],"type":"number"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.random.FakeHttpMessageInput":{"name":"Random HTTP message generator","requested_configuration":{"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"source":{"additional_info":{},"default_value":"example.org","description":"What to use as source of the generate messages.","human_name":"Source name","is_optional":false,"attributes":[],"type":"text"},"sleep":{"additional_info":{},"default_value":25,"description":"How many milliseconds to sleep between generating messages.","human_name":"Sleep time","is_optional":false,"attributes":["only_positive"],"type":"number"},"sleep_deviation":{"additional_info":{},"default_value":30,"description":"The deviation is used to generate a more realistic and non-steady message flow.","human_name":"Maximum random sleep time deviation","is_optional":false,"attributes":["only_positive"],"type":"number"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.raw.tcp.RawTCPInput":{"name":"Raw/Plaintext TCP","requested_configuration":{"port":{"additional_info":{},"default_value":5555,"description":"Port to listen on.","human_name":"Port","is_optional":false,"attributes":["is_port_number"],"type":"number"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"bind_address":{"additional_info":{},"default_value":"0.0.0.0","description":"Address to listen on. For example 0.0.0.0 or 127.0.0.1.","human_name":"Bind address","is_optional":false,"attributes":[],"type":"text"},"use_null_delimiter":{"additional_info":{},"default_value":false,"description":"Use null byte as frame delimiter? Default is newline.","human_name":"Null frame delimiter?","is_optional":true,"attributes":[],"type":"boolean"},"recv_buffer_size":{"additional_info":{},"default_value":1048576,"description":"The size in bytes of the recvBufferSize for network connections to this input.","human_name":"Receive Buffer Size","is_optional":true,"attributes":["only_positive"],"type":"number"},"max_message_size":{"additional_info":{},"default_value":2097152,"description":"The maximum length of a message.","human_name":"Maximum message size","is_optional":true,"attributes":["only_positive"],"type":"number"}},"exclusive":false,"link_to_docs":""},"org.graylog2.inputs.misc.metrics.LocalMetricsInput":{"name":"Internal metrics reporter","requested_configuration":{"duration_unit":{"additional_info":{"values":{"MINUTES":"Minutes","MILLISECONDS":"Milliseconds","DAYS":"Days","SECONDS":"Seconds","MICROSECONDS":"Microseconds","NANOSECONDS":"Nanoseconds","HOURS":"Hours"}},"default_value":"MILLISECONDS","description":"The time unit that will be used in for example timer values. Think of: took 15ms","human_name":"Time unit of measured durations","is_optional":false,"attributes":[],"type":"dropdown"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"source":{"additional_info":{},"default_value":"metrics","description":"Define a name of the source. For example 'metrics'.","human_name":"Source","is_optional":false,"attributes":[],"type":"text"},"report_unit":{"additional_info":{"values":{"MINUTES":"Minutes","MILLISECONDS":"Milliseconds","DAYS":"Days","SECONDS":"Seconds","MICROSECONDS":"Microseconds","NANOSECONDS":"Nanoseconds","HOURS":"Hours"}},"default_value":"SECONDS","description":null,"human_name":"Report interval unit","is_optional":false,"attributes":[],"type":"dropdown"},"rate_unit":{"additional_info":{"values":{"MINUTES":"Minutes","MILLISECONDS":"Milliseconds","DAYS":"Days","SECONDS":"Seconds","MICROSECONDS":"Microseconds","NANOSECONDS":"Nanoseconds","HOURS":"Hours"}},"default_value":"SECONDS","description":"The time unit that will be used in for example meter values. Think of: 7 per second","human_name":"Time unit of measured rates","is_optional":false,"attributes":[],"type":"dropdown"},"report_interval":{"additional_info":{},"default_value":10,"description":"Time between each report. Select a time unit in the corresponding dropdown.","human_name":"Report interval","is_optional":false,"attributes":["only_positive"],"type":"number"}},"exclusive":true,"link_to_docs":""},"org.graylog2.inputs.misc.jsonpath.JsonPathInput":{"name":"JSON path from HTTP API","requested_configuration":{"headers":{"additional_info":{},"default_value":"","description":"Add a comma separated list of additional HTTP headers. For example: Accept: application/json, X-Requester: Graylog2","human_name":"Additional HTTP headers","is_optional":true,"attributes":[],"type":"text"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"timeunit":{"additional_info":{"values":{"MINUTES":"Minutes","MILLISECONDS":"Milliseconds","DAYS":"Days","SECONDS":"Seconds","MICROSECONDS":"Microseconds","NANOSECONDS":"Nanoseconds","HOURS":"Hours"}},"default_value":"MINUTES","description":null,"human_name":"Interval time unit","is_optional":false,"attributes":[],"type":"dropdown"},"interval":{"additional_info":{},"default_value":1,"description":"Time between every collector run. Select a time unit in the corresponding dropdown. Example: Run every 5 minutes.","human_name":"Interval","is_optional":false,"attributes":[],"type":"number"},"source":{"additional_info":{},"default_value":"yourapi","description":"What to use as source field of the resulting message.","human_name":"Message source","is_optional":false,"attributes":[],"type":"text"},"path":{"additional_info":{},"default_value":"$.store.book[1].number_of_orders","description":"Path to the value you want to extract from the JSON response. Take a look at the documentation for a more detailled explanation.","human_name":"JSON path of data to extract","is_optional":false,"attributes":[],"type":"text"},"target_url":{"additional_info":{},"default_value":"http://example.org/api","description":"HTTP resource returning JSON on GET","human_name":"URI of JSON resource","is_optional":false,"attributes":[],"type":"text"}},"exclusive":false,"link_to_docs":"http://graylog2.org/resources/documentation/sending/jsonpath"},"org.graylog2.inputs.raw.udp.RawUDPInput":{"name":"Raw/Plaintext UDP","requested_configuration":{"port":{"additional_info":{},"default_value":5555,"description":"Port to listen on.","human_name":"Port","is_optional":false,"attributes":["is_port_number"],"type":"number"},"override_source":{"additional_info":{},"default_value":null,"description":"The source is a hostname derived from the received packet by default. Set this if you want to override it with a custom string.","human_name":"Override source","is_optional":true,"attributes":[],"type":"text"},"bind_address":{"additional_info":{},"default_value":"0.0.0.0","description":"Address to listen on. For example 0.0.0.0 or 127.0.0.1.","human_name":"Bind address","is_optional":false,"attributes":[],"type":"text"},"recv_buffer_size":{"additional_info":{},"default_value":1048576,"description":"The size in bytes of the recvBufferSize for network connections to this input.","human_name":"Receive Buffer Size","is_optional":true,"attributes":["only_positive"],"type":"number"}},"exclusive":false,"link_to_docs":""}}}; line: 1, column: 11] (through reference chain: org.graylog2.restclient.models.api.responses.system.InputTypesResponse["types"]->java.util.LinkedHashMap["org.graylog2.inputs.gelf.http.GELFHttpInput"])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[com.fasterxml.jackson.core.jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:749) ~[com.fasterxml.jackson.core.jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:59) ~[com.fasterxml.jackson.core.jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:12) ~[com.fasterxml.jackson.core.jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:451) ~[com.fasterxml.jackson.core.jackson-databind-2.4.3.jar:2.4.3]
[error] play - Cannot invoke the action, eventually got an error: org.graylog2.restclient.lib.Graylog2ServerUnavailableException
[error] application -

! @6ken2lg3l - Internal server error, for (GET) [/system/inputs] ->

play.api.Application$$anon$1: Execution exception[[Graylog2ServerUnavailableException: null]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.graylog2.restclient.lib.Graylog2ServerUnavailableException: null
        at org.graylog2.restclient.lib.ServerNodes.all(ServerNodes.java:73) ~[org.graylog2.graylog2-rest-client-0.93.0-SNAPSHOT.jar:na]
        at org.graylog2.restclient.lib.ServerNodes.master(ServerNodes.java:79) ~[org.graylog2.graylog2-rest-client-0.93.0-SNAPSHOT.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.onlyMasterNode(ApiClientImpl.java:315) ~[org.graylog2.graylog2-rest-client-0.93.0-SNAPSHOT.jar:na]
        at org.graylog2.restclient.models.NodeService.loadMasterNode(NodeService.java:62) ~[org.graylog2.graylog2-rest-client-0.93.0-SNAPSHOT.jar:na]
        at controllers.InputsController.index(InputsController.java:90) ~[graylog2-web-interface.graylog2-web-interface-0.93.0-SNAPSHOT.jar:0.93.0-SNAPSHOT]
```

Same error happens also when i go to existing Server node's Action->Details (or Input) dropdown.

p.s. I know that this is a snapshot version and might have some errors, but still i want to share it with you.

**Comment by kroepke** [comment]
this should be fixed
