### ISSUE TITLE
Ldap Connection Issue

### ISSUE THREAD

**Issue by thelordymir** [Graylog2/graylog2-web-interface#1019]
Using the Ldap connection tool via the webinterface, after plugging in config information and testing connectivity it fails.

Log shows this error

[error] o.g.r.m.a.LdapSettingsService - Unable to load LDAP settings.
org.graylog2.restclient.lib.APIException: API call failed GET http://@127.0.0.1:12900/system/ldap/settings returned 204 No Content body: 
	at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:404) ~[org.graylog2.graylog2-rest-client-0.90.0.jar:0.90.0]
	at org.graylog2.restclient.models.accounts.LdapSettingsService.load(LdapSettingsService.java:48) ~[org.graylog2.graylog2-rest-client-0.90.0.jar:0.90.0]
	at controllers.LdapController.index(LdapController.java:51) [graylog2-web-interface.graylog2-web-interface-0.90.0.jar:0.90.0]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$105$$anonfun$apply$313.apply(routes_routing.scala:1533) [graylog2-web-interface.graylog2-web-interface-0.90.0.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$105$$anonfun$apply$313.apply(routes_routing.scala:1533) [graylog2-web-interface.graylog2-web-interface-0.90.0.jar:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]

Something that can be fixed via upgrading or am I missing something in my config? Thanks

**Comment by joschi** [comment]
Please check the display name attribute of your LDAP settings and that this attribute actually exists for the user account in question in your LDAP directory.

Refs Graylog2/graylog2-server#837

**Comment by thelordymir** [comment]
It does seem that was the issue, upgrading to the newest graylog and making sure a display name attribute existed allows authentication and lets me be able to go back in and view all users who have logged in and apply permissions/dashboards to them. Thank you. Closing as it's fixed.
