### ISSUE TITLE
Unable to login to latest graylog2 web snapshot

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#1021]
Hi,

Running graylog2-0.93.0-SNAPSHOT-20150103110407 & graylog2-web-interface-0.93.0-SNAPSHOT-20150104163116.

I cannot login to webinterface. Browser says:
"We discovered Graylog2 servers but could not reach any. Please check your log file.(IOException) "

And graylog-web-interface fires this error:

[error] c.SessionsController - Error when trying to reach Graylog2 servers.
com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.graylog2.restclient.models.api.requests.SessionCreateRequest and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2881) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2338) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]

Emptied ES and mongo, but still same error at login.

Seems that there some issues with sessions. 
If i login through graylog2-web-interface-0.93.0-SNAPSHOT-20141211141122, stop it, start graylog2-web-interface-0.93.0-SNAPSHOT-20150104163116, then i can use web interface without problems.

But when i logout from (graylog2-web-interface-0.93.0-SNAPSHOT-20150104163116), then i cannot login anymore.

Ideas about that?

**Comment by dennisoelkers** [comment]
Thanks for reporting this. This is supposed to be fixed in Graylog2/graylog2-server@3cb712181008916c88ebfaf3142a2c241c361562, so the next snapshots should be fine again.

**Comment by dennisoelkers** [comment]
Reverted Graylog2/graylog2-server@3cb712181008916c88ebfaf3142a2c241c361562 and fixed it properly.
