### ISSUE TITLE
Unable to save user's preferences.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#1027]
Hi,

i'm unable to save users' preferences:
```
# [error] o.g.r.m.UserService - Could not save preferences for xxxxxx
com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.graylog2.restclient.models.UserService$1 and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3383) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2777) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
```

This happens with graylog2-0.93.0-SNAPSHOT-20150111232629 & graylog2-web-interface-0.93.0-SNAPSHOT-20150109102759.

**Comment by kroepke** [comment]
Need to check all resource classes for JsonCreator annotations.

**Comment by sebclick** [comment]
Same error on Graylog2 1.0 beta : 

```
2015-01-13 11:50:48,220 - [ERROR] - from org.graylog2.restclient.models.UserService in play-akka.actor.default-dispatcher-115 
Could not save preferences for xxx
com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.graylog2.restclient.models.UserService$1 and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
```

**Comment by timukas** [comment]
As a quick workaround you can update user's data directly in mongo.
  "preferences": {
    "updateUnfocussed": false,
    "disableExpensiveUpdates": true,
    "enableSmartSearch": true
  },

**Comment by kroepke** [comment]
THX!

**Comment by sebclick** [comment]
Yes it works. Thx ! :smile:

**Comment by killswordfish** [comment]
How do you update user's data directly in mango? Can you provide the steps. I am new and not familiar with Mongo.

**Comment by edmundoa** [comment]
Hi @killswordfish,

Usually you shouldn't update the data directly in MongoDB unless you really know what you are doing. Are you experiencing any problems changing user preferences with the web interface? Please keep in mind that the `admin` user haven't got preferences.
