### ISSUE TITLE
Content pack permissions

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-web-interface#1033]
When logged in as non-admin user, I can see the "Create content pack" button on the content packs page. Clicking the button results in an exception.

```
! @6kol7c8bp - Internal server error, for (GET) [/system/contentpacks/export] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.6.jar:2.3.6]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145) [scala-library.jar:na]
Caused by: java.lang.NullPointerException: null
        at views.html.system.bundles.export$$anonfun$1$$anonfun$apply$4.apply(export.template.scala:115) ~[classes/:na]
        at views.html.system.bundles.export$$anonfun$1$$anonfun$apply$4.apply(export.template.scala:111) ~[classes/:na]
        at play.twirl.api.TemplateMagic$.defining(TemplateMagic.scala:13) ~[twirl-api_2.10-1.0.2.jar:1.0.2]
        at views.html.system.bundles.export$$anonfun$1.apply(export.template.scala:111) ~[classes/:na]
        at views.html.system.bundles.export$$anonfun$1.apply(export.template.scala:64) ~[classes/:na]
```
On the server I see the following.

```
2015-01-14 20:58:13,942 INFO : org.graylog2.shared.security.ShiroAuthorizationFilter - User not authorized.
org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [stream_outputs:create]
	at org.apache.shiro.authz.ModularRealmAuthorizer.checkPermission(ModularRealmAuthorizer.java:323)
	at org.apache.shiro.mgt.AuthorizingSecurityManager.checkPermission(AuthorizingSecurityManager.java:137)
	at org.apache.shiro.subject.support.DelegatingSubject.checkPermission(DelegatingSubject.java:205)
	at org.apache.shiro.authz.aop.PermissionAnnotationHandler.assertAuthorized(PermissionAnnotationHandler.java:74)
	at org.graylog2.shared.security.ShiroAuthorizationFilter.filter(ShiroAuthorizationFilter.java:49)
```
I guess there are some missing checks for permissions in the web interface. Not sure if a regular user should even see the content pack management.

**Comment by kroepke** [comment]
Right, there are permission checks failing in other parts as well.
