### ISSUE TITLE
Failed instance of global input leads to NPE in web interface on node overview page

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#1054]
```

! @6l0i99d2c - Internal server error, for (GET) [/a/system/inputs/global/54bfaf49bee88b8570c76544/io] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
Caused by: java.lang.NullPointerException: null
	at org.graylog2.restclient.models.ClusterService.asLong(ClusterService.java:189) ~[graylog2-rest-client-1.0.0-beta.3-SNAPSHOT.jar:na]
	at org.graylog2.restclient.models.ClusterService.getGlobalInputIo(ClusterService.java:232) ~[graylog2-rest-client-1.0.0-beta.3-SNAPSHOT.jar:na]
	at controllers.api.InputsApiController.globaIO(InputsApiController.java:93) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$149$$anonfun$apply$809.apply(routes_routing.scala:2517) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$149$$anonfun$apply$809.apply(routes_routing.scala:2517) ~[classes/:na]
```

**Comment by kroepke** [comment]
Also, trying to delete global inputs where one instance is failed works only if the server's have not been restarted in between.

Steps to reproduce:

 * Start two server instances on one machine.
 * Start a global network input, to make one fail, because both will try to bind to the same port.
 * The inputs overview will show "1 running", but "1 failed" is missing.
 * Deleting the global input now works.
 * Repeat the first steps but do not delete input, instead restart both servers.
 * When both are up again, reload inputs overview page, it now shows "1 failed" "1 running" badges.
 * There are NPEs as in the original comment in this issue.
 * Delete the global input, the failed IOState will not get removed, leading to: "[error] c.a.InputsApiController - Could not load input." in the web interface.
  * The input is removed from mongodb but apparently some state is not being cleaned up. A server restart naturally fixes this problem.

**Comment by kroepke** [comment]
also:
```
2015-01-21 15:21:53,247 ERROR: org.graylog2.plugin.rest.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.NullPointerException
	at org.graylog2.inputs.InputServiceImpl.findForThisNodeOrGlobal(InputServiceImpl.java:130)
	at org.graylog2.rest.resources.system.inputs.InputsResource.launchExisting(InputsResource.java:321)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kroepke** [comment]
The second issue of missing inputs on the second node is caused by my configuration.

I had master = true in both config files, and the second server detects another master, but still announces itself as master via /cluster/nodes.
This causes the web interface to skip it when launching the global input.

As having two masters isn't supported nor recommended, we will ignore this problem for the moment. 

The cluster state problem must be solved anyway, so we can address this problem there as well.

**Comment by oinadmin** [comment]
problem solved?
