### ISSUE TITLE
Adding field presence stream rule fails on Firefox

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-web-interface#1095]
Steps to reproduce:

* Go to Streams
* Click "Edit rules" on an arbitrary stream
* Click "Add stream rule"
* Select "field presence" for the type
* Enter an arbitrary field name
* Click "Save"

Expected result:
* Dialog closes
* Stream rule is created

Actual result:
* Dialog stays open
* "Please fill out this field" tooltip appears

**Comment by dennisoelkers** [comment]
Firefox version is 35.0.1 on Mac OS X 10.10

**Comment by dfch** [comment]
Just to let you know and confirm. It is working in RC2 again. Thanks!

**Comment by edmundoa** [comment]
Good to hear! Thank you for your feedback @dfch!

**Comment by ikramkhan544** [comment]
unable to start the graylog service please review it and find some soluiton 



2015-02-09 22:19:15,426 INFO : org.graylog2.shared.initializers.RestApiService - Started REST API at <http://127.0.0.1:12900/>
2015-02-09 22:19:15,427 INFO : org.graylog2.shared.initializers.RestApiService - Shutting down REST API at <http://127.0.0.1:12900/>
2015-02-09 22:19:15,431 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are now stopped.
2015-02-09 22:19:15,432 ERROR: org.graylog2.Main - Graylog2 startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[RestApiService [STARTING]], FAILED=[IndexerSetupService [FAILED]]}
        at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:710)
        at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:535)
        at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:301)
        at org.graylog2.Main.main(Main.java:275)
2015-02-09 22:19:15,434 INFO : org.graylog2.Main - SIGNAL received. Shutting down.
2015-02-09 22:19:15,445 ERROR: org.graylog2.periodical.AbstractCacheWorkerThread - Exception while working on cache:
java.lang.IllegalStateException: Error while accessing database
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:191)
        at org.graylog2.periodical.AbstractCacheWorkerThread.drainMessagesEnqueue(AbstractCacheWorkerThread.java:75)
        at org.graylog2.periodical.AbstractCacheWorkerThread.work(AbstractCacheWorkerThread.java:58)
        at org.graylog2.periodical.OutputCacheWorkerThread$1.run(OutputCacheWorkerThread.java:60)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
        at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.Atomic$Long.get(Atomic.java:315)
        at org.mapdb.Queues$SimpleQueue.poll(Queues.java:127)
        at org.mapdb.Queues$SimpleQueue.take(Queues.java:243)
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
        ... 4 more
2015-02-09 22:19:15,459 ERROR: org.graylog2.periodical.AbstractCacheWorkerThread - Exception while working on cache:
java.lang.IllegalStateException: Error while accessing database
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:191)
        at org.graylog2.periodical.AbstractCacheWorkerThread.drainMessagesEnqueue(AbstractCacheWorkerThread.java:75)
        at org.graylog2.periodical.AbstractCacheWorkerThread.work(AbstractCacheWorkerThread.java:58)
        at org.graylog2.periodical.InputCacheWorkerThread$1.run(InputCacheWorkerThread.java:60)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
        at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.Atomic$Long.get(Atomic.java:315)
        at org.mapdb.Queues$SimpleQueue.poll(Queues.java:127)
        at org.mapdb.Queues$SimpleQueue.take(Queues.java:243)
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
        ... 4 more
2015-02-09 22:19:15,525 INFO : org.graylog2.system.shutdown.GracefulShutdown - Graceful shutdown initiated.
2015-02-09 22:19:15,525 INFO : org.graylog2.system.shutdown.GracefulShutdown - Node status: [Halting [LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
2015-02-09 22:19:19,539 INFO : org.graylog2.system.shutdown.GracefulShutdown - Goodbye.
