### ISSUE TITLE
unable to exports events more than 10000 in csv file 

### ISSUE THREAD

**Issue by ikramkhan544** [Graylog2/graylog2-web-interface#1107]

**Comment by ikramkhan544** [comment]
please hepl me to collect full report of 1 month with proper timestamp in graylog web interface

**Comment by kroepke** [comment]
The web interface currently does not support more than 10,000 results. You can use the server's REST API to retrieve more.

Unforunately those results won't be sorted, due to the underlying technology used.

**Comment by ikramkhan544** [comment]
im new to graqylog2 can u suggest me some queries to fetch logs from graylog2 ex account lock out logs , audit logs , critical evetnt logs please

**Comment by kroepke** [comment]
I'm sorry, but we won't be able to help write queries. I suggest you try to get assistance of that kind on in our Google Group: https://groups.google.com/forum/?fromgroups=#!forum/graylog2

**Comment by ikramkhan544** [comment]
unable to start graylog2 service this is the error message im getting 



2015-02-09 22:19:15,426 INFO : org.graylog2.shared.initializers.RestApiService - Started REST API at <http://127.0.0.1:12900/>
2015-02-09 22:19:15,427 INFO : org.graylog2.shared.initializers.RestApiService - Shutting down REST API at <http://127.0.0.1:12900/>
2015-02-09 22:19:15,431 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are now stopped.
2015-02-09 22:19:15,432 ERROR: org.graylog2.Main - Graylog2 startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[RestApiService [STARTING]], FAILED=[IndexerSetupService [FAILED]]}
        at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:710)
        at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:535)
        at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:301)
        at org.graylog2.Main.main(Main.java:275)
2015-02-09 22:19:15,434 INFO : org.graylog2.Main - SIGNAL received. Shutting down.
2015-02-09 22:19:15,445 ERROR: org.graylog2.periodical.AbstractCacheWorkerThread - Exception while working on cache:
java.lang.IllegalStateException: Error while accessing database
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:191)
        at org.graylog2.periodical.AbstractCacheWorkerThread.drainMessagesEnqueue(AbstractCacheWorkerThread.java:75)
        at org.graylog2.periodical.AbstractCacheWorkerThread.work(AbstractCacheWorkerThread.java:58)
        at org.graylog2.periodical.OutputCacheWorkerThread$1.run(OutputCacheWorkerThread.java:60)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
        at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.Atomic$Long.get(Atomic.java:315)
        at org.mapdb.Queues$SimpleQueue.poll(Queues.java:127)
        at org.mapdb.Queues$SimpleQueue.take(Queues.java:243)
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
        ... 4 more
2015-02-09 22:19:15,459 ERROR: org.graylog2.periodical.AbstractCacheWorkerThread - Exception while working on cache:
java.lang.IllegalStateException: Error while accessing database
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:191)
        at org.graylog2.periodical.AbstractCacheWorkerThread.drainMessagesEnqueue(AbstractCacheWorkerThread.java:75)
        at org.graylog2.periodical.AbstractCacheWorkerThread.work(AbstractCacheWorkerThread.java:58)
        at org.graylog2.periodical.InputCacheWorkerThread$1.run(InputCacheWorkerThread.java:60)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
        at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.Atomic$Long.get(Atomic.java:315)
        at org.mapdb.Queues$SimpleQueue.poll(Queues.java:127)
        at org.mapdb.Queues$SimpleQueue.take(Queues.java:243)
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
        ... 4 more
2015-02-09 22:19:15,525 INFO : org.graylog2.system.shutdown.GracefulShutdown - Graceful shutdown initiated.
2015-02-09 22:19:15,525 INFO : org.graylog2.system.shutdown.GracefulShutdown - Node status: [Halting [LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
2015-02-09 22:19:19,539 INFO : org.graylog2.system.shutdown.GracefulShutdown - Goodbye.
