### ISSUE TITLE
ClassCastException when searching

### ISSUE THREAD

**Issue by Spea** [Graylog2/graylog2-web-interface#1218]
Hey there,

I'm using version 1.0.0 and when I search for the term `13200458` I get the following exception_
```bash
[error] play - Cannot invoke the action, eventually got an error: java.lang.ClassCastException
[error] application -

! @6lpfk11ja - Internal server error, for (GET) [/search?rangetype=relative&fields=&width=1920&relative=0&from=&to=&q=13200458] ->

play.api.Application$$anon$1: Execution exception[[ClassCastException: null]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.ClassCastException: null
```

It looks like there is an invalid message in one of the facilites we use, because when I add the filter `NOT facility:$myFacility` everything works fine. Sadly the relevant messages I need are in this facility :)

I also checked the server logs, but there were no exceptions, so it is related to the web-interface.

If you need anything else, let me know

**Comment by edmundoa** [comment]
Hi,

Sorry it took so long to get back to you. Is this still an issue for you?

**Comment by Spea** [comment]
Hey,

I haven't had this issue since the upgrade to the newest version, thx :)
