### ISSUE TITLE
 /system/indices shows 109 indices with a total of 0 messages under management.

### ISSUE THREAD

**Issue by HSVK** [Graylog2/graylog2-web-interface#1221]
The Indice does not show the message count, i have recalculated the index and also recycled the deflector. Its still the same. "109 indices with a total of 0 messages under management."
Also under source menu, i get the graphs and the all other details, but on the right i see "Containing 0 events.". I am pretty sure i have been seeing the number of messages being listed there. 

Right now we have set up to open 180 indices with 12 hr / indice. I checked the memory details they all seem to be Ok. We am using v 1.0.0, can you please help us. 

Regards, Hema

**Comment by edmundoa** [comment]
Hi,

Sorry it took so long to reply to this. Is this still an issue?

**Comment by HSVK** [comment]
Hi Edmudoa, Yes i still have this issue. I have also upgraded to the latest version of 1.1.5 and elasticsearch to 1.6.2. But i still could not see the number of messages under management.

**Comment by edmundoa** [comment]
Could you please share with us the result of `http://<graylog-server-host>:12900/count/total` and any errors that may appear in the graylog server logs while executing that query? Maybe that will help to see where the issue is.

**Comment by HSVK** [comment]
Hi Edmundoa, 
   Here are the details, 

Output of http://<graylog-server-host>:12900/count/total
{"events":16164175618}

In server.log I only see this when the query is running..

2015-08-14T03:35:24.930-06:00 WARN  [KafkaJournal] Offset out of range, no messages available starting at offset 2002831004
2015-08-14T03:43:03.767-06:00 WARN  [KafkaJournal] Offset out of range, no messages available starting at offset 2002888614

I ran the query again, but there were no new entries in the log. 

Please let me know if you want me to get any output.

Thanks, Hema

**Comment by edmundoa** [comment]
The log messages don't seem to be related to the issue, and the response from the server looks also good to me.

My current guess is that the query takes too long for some reason and times out. Could you please open your browser's web developer tools and navigate to the indices page? I'm specially interested in any errors you may see in the console tab, and also in the result of the requests to `/a/messagecounts/total` that you can find in the network tab. Here's an screen shot of how one of those requests looks like in Chrome:
<img width="1139" alt="screen shot 2015-08-14 at 12 25 29" src="https://cloud.githubusercontent.com/assets/716185/9272159/f0419224-427f-11e5-816a-d8a0b3dbd8bc.png">

**Comment by HSVK** [comment]
Hi Edmundoa,
    I am getting a 404 error when trying to reach <graylog-server>:12900/a/messagecounts/total, But here is the network details for <graylog-server>:12900/count/total/ 

![image](https://cloud.githubusercontent.com/assets/12095535/9301794/c47dc2e0-44ee-11e5-9626-9616981e7fb3.png)

**Comment by edmundoa** [comment]
Hi HSVK,

The resource `/a/messagecounts/total` is only available in the web interface, so that 404 is actually normal. What I meant is that you should try to open the indices page again in the Graylog web interface, while having the network tab of your browser's web developer tools open. Then check what the result of `/a/messagecounts/total` is (see my screen shot above for an example), as that should return the value that is included into the page. Of course share with us any error logs that you may see in the process.

**Comment by HSVK** [comment]
Hi Edmundoa,
   Here is the screenshot when i land in the indice page, and i do not see any errors in the graylog server. 
Here are the logs that i see in graylog webserver, but this entry occurs frequently.. 

application.log:  2015-08-18T04:00:34.990-06:00 - [ERROR] - from org.graylog2.restclient.models.MessagesService in play-akka.actor.default-dispatcher-5
Could not load total message count
org.graylog2.restclient.lib.APIException: API call failed GET http://@xx.xx.xx.xxx:12900/count/total
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:451) ~[org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        at org.graylog2.restclient.models.MessagesService$2.call(MessagesService.java:90) ~[org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        at org.graylog2.restclient.models.MessagesService$2.call(MessagesService.java:87) ~[org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        at play.cache.Cache.getOrElse(Cache.java:34) ~[com.typesafe.play.play-cache_2.10-2.3.9.jar:2.3.9]
        at org.graylog2.restclient.models.MessagesService.total(MessagesService.java:87) ~[org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        at controllers.MessageCountsController.total(MessageCountsController.java:38) [graylog-web-interface.graylog-web-interface-1.1.5.jar:1.1.5]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$130$$anonfun$apply$828.apply(routes_routing.scala:2643) [graylog-web-interface.graylog-web-interface-1.1.5.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$130$$anonfun$apply$828.apply(routes_routing.scala:2643) [graylog-web-interface.graylog-web-interface-1.1.5.jar:na]
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.GlobalSettings$1.call(GlobalSettings.java:67) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.mvc.Security$AuthenticatedAction.call(Security.java:44) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.impl.Future$.apply(Future.scala:31) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: No response received after 5000
        at com.ning.http.client.providers.netty.NettyResponseFuture.get(NettyResponseFuture.java:266) ~[com.ning.async-http-client-1.8.14.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:435) ~[org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        ... 45 common frames omitted
Caused by: java.util.concurrent.TimeoutException: No response received after 5000
        at com.ning.http.client.providers.netty.NettyResponseFuture.get(NettyResponseFuture.java:260) ~[com.ning.async-http-client-1.8.14.jar:na]
        ... 46 common frames omitted

2015-08-18T04:00:42.521-06:00 - [ERROR] - from org.graylog2.restclient.lib.ApiClient in play-akka.actor.default-dispatcher-7
REST call failed
java.util.concurrent.TimeoutException: No response received after 5000
 at com.ning.http.client.providers.netty.NettyResponseFuture.get(NettyResponseFuture.java:260) ~[com.ning.async-http-client-1.8.14.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:435) ~[org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        at org.graylog2.restclient.models.MessagesService$2.call(MessagesService.java:90) [org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        at org.graylog2.restclient.models.MessagesService$2.call(MessagesService.java:87) [org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        at play.cache.Cache.getOrElse(Cache.java:34) [com.typesafe.play.play-cache_2.10-2.3.9.jar:2.3.9]
        at org.graylog2.restclient.models.MessagesService.total(MessagesService.java:87) [org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]
        at controllers.MessageCountsController.total(MessageCountsController.java:38) [graylog-web-interface.graylog-web-interface-1.1.5.jar:1.1.5]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$130$$anonfun$apply$828.apply(routes_routing.scala:2643) [graylog-web-interface.graylog-web-interface-1.1.5.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$130$$anonfun$apply$828.apply(routes_routing.scala:2643) [graylog-web-interface.graylog-web-interface-1.1.5.jar:na]
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.GlobalSettings$1.call(GlobalSettings.java:67) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.mvc.Security$AuthenticatedAction.call(Security.java:44) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.impl.Future$.apply(Future.scala:31) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]

2015-08-18T04:00:42.523-06:00 - [ERROR] - from org.graylog2.restclient.models.MessagesService in play-akka.actor.default-dispatcher-7
Could not load total message count
org.graylog2.restclient.lib.APIException: API call failed GET http://@xx.xx.xx.xx:12900/count/total
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:451) ~[org.graylog2.graylog2-rest-client--1.1.5-1.1.5.jar:na]




![image](https://cloud.githubusercontent.com/assets/12095535/9327129/35d985c8-45bc-11e5-81e0-22509992aeee.png)

**Comment by edmundoa** [comment]
Hi,

It looks like your Elasticsearch cluster is taking too much time to return the total number of messages stored, that's why you see a 0 in the Graylog web interface. That means that the value displayed in Graylog is wrong, but your messages are stored in ES.

**Comment by HSVK** [comment]
Hi Edmundoa, 
  Ok, can you please advise on how to resolve. 

Thanks, Hema.

**Comment by joschi** [comment]
@HSVK You can increase the default timeout being used by the Graylog web interface to communicate with a Graylog server node (see https://github.com/Graylog2/graylog2-web-interface/blob/38d6140b8f743ac0e15e8596ec3b51782459e4f1/misc/graylog-web-interface.conf.example#L31-L32).

To improve the performance of your Elasticsearch cluster, it might help to add additional ES nodes and use more shards (distributed on all nodes).

In general, please use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for support questions.

**Comment by HSVK** [comment]
Hi Joschi,
  We already have 3 elasticsearch boxes with 4 Shard allocation in total. And do not see any issues in ES w.r.t out of memory. What is the shard that you propose that we can increase to? 
Meanwhile i just increased the graylog web interface default of 5s to 20s now. Would you recommend this timing? Will check for few days and will let you know the status. 

Thanks, Hema.
