### ISSUE TITLE
WriteConcernException: cannot remove from a capped collection: graylog2.cluster_events

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1246]
Running current `master` I am getting this periodically:

```
2015-04-28 20:25:24,064 WARN : org.graylog2.events.ClusterEventCleanupPeriodical - Error while removing stale cluster events from MongoDB
com.mongodb.WriteConcernException: { "serverUsed" : "localhost:27017" , "ok" : 1 , "n" : 0 , "err" : "cannot remove from a capped collection: graylog2.cluster_events" , "code" : 20}
	at com.mongodb.CommandResult.getWriteException(CommandResult.java:90)
	at com.mongodb.CommandResult.getException(CommandResult.java:79)
	at com.mongodb.DBCollectionImpl.translateBulkWriteException(DBCollectionImpl.java:316)
	at com.mongodb.DBCollectionImpl.remove(DBCollectionImpl.java:228)
	at com.mongodb.DBCollectionImpl.remove(DBCollectionImpl.java:203)
	at com.mongodb.DBCollection.remove(DBCollection.java:300)
	at org.mongojack.JacksonDBCollection.remove(JacksonDBCollection.java:726)
	at org.graylog2.events.ClusterEventCleanupPeriodical.doRun(ClusterEventCleanupPeriodical.java:107)
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by lennartkoopmann** [comment]
```
> db.cluster_events.stats()
{
	"ns" : "graylog2.cluster_events",
	"count" : 0,
	"size" : 0,
	"numExtents" : 1,
	"storageSize" : 32768,
	"lastExtentSize" : 32768,
	"paddingFactor" : 1,
	"paddingFactorNote" : "paddingFactor is unused and unmaintained in 3.0. It remains hard coded to 1.0 for compatibility only.",
	"userFlags" : 1,
	"capped" : true,
	"max" : NumberLong("9223372036854775807"),
	"maxSize" : 32768,
	"nindexes" : 4,
	"totalIndexSize" : 32704,
	"indexSizes" : {
		"_id_" : 8176,
		"producer_1" : 8176,
		"consumers_1" : 8176,
		"timestamp_1_producer_1_consumers_1" : 8176
	},
	"ok" : 1
}
```

**Comment by joschi** [comment]
Remove the `cluster_events` collection from your MongoDB database manually. The capped collection was only used for a short time and has been replaced by a non-capped collection.

You should also see a WARNING in your Graylog logs about this.
