### ISSUE TITLE
Invalid range parameters of widget in dashboard

### ISSUE THREAD

**Issue by rockaut** [Graylog2/graylog2-web-interface#1505]
I updated from 1.0.0-4 to 1.1.3 and got this error in server/current log. I have some widgets with time searches "since 00:00:00+2h" which worked in 1.0.0. Now i have to use "since 00:00:00+2" ... i have to redo all dashboards with such widgets because changing existing brings an "Gateway Timeout" error on page.
```
2015-06-24_09:31:23.90195 ERROR [DashboardServiceImpl] Invalid range parameters of widget in dashboard: [55365658e4b041485e234e9d]
2015-06-24_09:31:23.90196 org.graylog2.indexer.searches.timeranges.InvalidRangeParametersException: Could not parse from natural date: since 00:00:00+2h
2015-06-24_09:31:23.90196       at org.graylog2.indexer.searches.timeranges.KeywordRange.<init>(KeywordRange.java:48)
2015-06-24_09:31:23.90197       at org.graylog2.dashboards.widgets.DashboardWidgetCreator.fromPersisted(DashboardWidgetCreator.java:113)
2015-06-24_09:31:23.90197       at org.graylog2.dashboards.DashboardServiceImpl.all(DashboardServiceImpl.java:96)
2015-06-24_09:31:23.90197       at org.graylog2.rest.resources.dashboards.DashboardsResource.list(DashboardsResource.java:138)
2015-06-24_09:31:23.90198       at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
2015-06-24_09:31:23.90198       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-06-24_09:31:23.90198       at java.lang.reflect.Method.invoke(Method.java:497)
2015-06-24_09:31:23.90199       at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
2015-06-24_09:31:23.90199       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164)
2015-06-24_09:31:23.90200       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181)
2015-06-24_09:31:23.90201       at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:203)
2015-06-24_09:31:23.90201       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101)
2015-06-24_09:31:23.90202       at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
2015-06-24_09:31:23.90202       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
2015-06-24_09:31:23.90203       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
2015-06-24_09:31:23.90203       at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)
2015-06-24_09:31:23.90203       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
2015-06-24_09:31:23.90204       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
2015-06-24_09:31:23.90204       at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
2015-06-24_09:31:23.90205       at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
2015-06-24_09:31:23.90206       at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
2015-06-24_09:31:23.90207       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
2015-06-24_09:31:23.90207       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
2015-06-24_09:31:23.90208       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
2015-06-24_09:31:23.90208       at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
2015-06-24_09:31:23.90208       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
2015-06-24_09:31:23.90209       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
2015-06-24_09:31:23.90209       at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
2015-06-24_09:31:23.90210       at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
2015-06-24_09:31:23.90210       at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
2015-06-24_09:31:23.90211       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2015-06-24_09:31:23.90212       at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
2015-06-24_09:31:23.90212       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-06-24_09:31:23.90212       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-06-24_09:31:23.90213       at java.lang.Thread.run(Thread.java:745)
```

**Comment by edmundoa** [comment]
Hi,

We use [natty](http://natty.joestelmach.com/) to parse natural dates, and it seems that new versions don't support specifying a time zone with `+2h` any more. That causes Graylog to have problems parsing the widget date, and in the end is not even possible to edit the widget, as Graylog server returns a 404, which is no doubt a bug on our side.

As a workaround, it is possible to edit the widgets with those problematic time ranges in MongoDB directly.
