### ISSUE TITLE
Please redirect to login page when session is expired

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-web-interface#1507]
Hello,

Actually when session is expired, all background/foreground JS continue to call graylog-server API which silently and massively throws following errors
```
2015-06-25T09:42:41.450Z - [WARN] - from controllers.api.MetricsController in pool-3840368-thread-1
Unable to load metrics
org.graylog2.restclient.lib.APIException: API call failed POST https://@xxxxxxxxxx:12900/system/metrics/multiple returned 401 Unauthorized body:
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.handleResponse(ApiClientImpl.java:508) ~[org.graylog2.graylog2-rest-client--1.1.0-1.1.0.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.executeOnAll(ApiClientImpl.java:607) ~[org.graylog2.graylog2-rest-client--1.1.0-1.1.0.jar:na]
        at controllers.api.MetricsController$PollingJob.run(MetricsController.java:117) ~[graylog-web-interface.graylog-web-interface-1.1.0.jar:1.1.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```
If you have dozens of users, log file grows a lot, and calling indefinitely graylog server to handle auth requests is not very useful.

So in my opinion, you should redirect user to login page when session expires, and so stop all background JS calls.

Thanks.

**Comment by ghost** [comment]
Same here, a lot of log activity due to this

**Comment by edmundoa** [comment]
This behaviour changed in the upcoming 2.0.0, please try the beta version and reopen if this is still an issue.

Thank you!
