### ISSUE TITLE
  Error executing action `run` on resource 'ruby_block[add node to server list]

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/graylog2-web-interface#1549]
After upgrade from v 1.1.4 to 1.1.5 and reconfiguring graylog, i got the failure decribed above:
 
 ruby_block[add node to server list] action run
    ================================================================================
    Error executing action `run` on resource 'ruby_block[add node to server list]'
    ================================================================================

    Errno::ECONNREFUSED
    -------------------
    Connection refused - connect(2) for "127.0.0.1" port 4001

    Cookbook Trace:
    ---------------
    /opt/graylog/embedded/cookbooks/graylog/libraries/registry.rb:17:in `set_master'
    /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:81:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb

     79: ruby_block "add node to server list" do
     80:   block do
     81:     $registry.set_master
     82:     $registry.add_gl_server(node['ipaddress'])
     83:     $registry.add_es_node(node['ipaddress'])
     84:   end
     85: end

    Compiled Resource:
    ------------------
    # Declared in /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:79:in `from_file'

    ruby_block("add node to server list") do
      action "run"
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "add node to server list"
      declared_type :ruby_block
      cookbook_name :graylog
      recipe_name "graylog-server"
      block #<Proc:0x000000042ee4e8@/opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:80>
    end

Running handlers:
[2015-07-31T10:00:16+02:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-31T10:00:16+02:00] ERROR: Exception handlers complete
[2015-07-31T10:00:16+02:00] FATAL: Stacktrace dumped to /opt/graylog/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 6 resources updated in 5.707804974 seconds
[2015-07-31T10:00:16+02:00] ERROR: ruby_block[add node to server list] (graylog::graylog-server line 79) had an error: Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 4001
[2015-07-31T10:00:16+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Graylog seems running, because i get some stream alerts, but WEB-GUI can not be opened.
I tested "sudo graylog-ctl restart etcd". 
Message after restart: ok: run: etcd: (pid 14919) 0s
Then looked for errors in log with "sudo graylog-ctl tail etcd". This is my result (Logs entry every second):
2015-08-06_07:29:15.71893 2015/08/06 09:29:15 etcdserver: read wal error: unexpected EOF
2015-08-06_07:29:16.72284 2015/08/06 09:29:16 etcd: already initialized as member before, starting as etcd member...
2015-08-06_07:29:16.72381 2015/08/06 09:29:16 etcd: listening for peers on http://localhost:2380
2015-08-06_07:29:16.72386 2015/08/06 09:29:16 etcd: listening for peers on http://localhost:7001
2015-08-06_07:29:16.72390 2015/08/06 09:29:16 etcd: listening for client requests on http://0.0.0.0:2379
2015-08-06_07:29:16.72394 2015/08/06 09:29:16 etcd: listening for client requests on http://0.0.0.0:4001
2015-08-06_07:29:16.72403 2015/08/06 09:29:16 etcdserver: datadir is valid for the 2.0.1 format
2015-08-06_07:29:16.72679 2015/08/06 09:29:16 etcdserver: recovered store from snapshot at index 9150915
2015-08-06_07:29:16.72687 2015/08/06 09:29:16 etcdserver: name = default
2015-08-06_07:29:16.72689 2015/08/06 09:29:16 etcdserver: data dir = /var/opt/graylog/data/etcd
2015-08-06_07:29:16.72691 2015/08/06 09:29:16 etcdserver: member dir = /var/opt/graylog/data/etcd/member
2015-08-06_07:29:16.72692 2015/08/06 09:29:16 etcdserver: heartbeat = 100ms
2015-08-06_07:29:16.72694 2015/08/06 09:29:16 etcdserver: election = 1000ms
2015-08-06_07:29:16.72695 2015/08/06 09:29:16 etcdserver: snapshot count = 10000
2015-08-06_07:29:16.72697 2015/08/06 09:29:16 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015-08-06_07:29:16.72700 2015/08/06 09:29:16 etcdserver: loaded cluster information from store: default=http://localhost:2380,default=http://localhost:7001

so, what todo?

**Comment by joschi** [comment]
Please use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general questions about Graylog and its sub-projects.

**Comment by plt-sun** [comment]
Wonderfull! this was my third try to get help for this problem. everyone moved it to antoher :-(

**Comment by joschi** [comment]
@plt-sun I've seen Graylog2/graylog2-server#1331 and Graylog2/graylog2-cookbook#35. Nevertheless, please post your problem to the mailing list as we try to keep using GitHub issues only for bug reports and limited feature requests.

**Comment by plt-sun** [comment]
ok. Done.
