### ISSUE TITLE
No Graylog servers available. Cannot log in.

### ISSUE THREAD

**Issue by shiyamk** [Graylog2/graylog2-web-interface#1556]
Hi,

Great app, i have installed it in my laptop as appliance works well. but when i try to install in Hyper-V as ubuntu package im having issues with the graylog-web.

used the latest version of graylog-server and raylog-web. elasticsearch 1.3.7, mongodb latest and java 7.

graylog server log shows 
2015-08-17T06:54:05.762+01:00 INFO  [ServerBootstrap] Graylog server up and running.

but graylog-web log shows:
2015-08-17T06:56:07.929+01:00 - [ERROR] - from org.graylog2.restclient.lib.ServerNodesRefreshService in servernodes-refresh-0
Resolving configured nodes failed
java.lang.IllegalArgumentException: Schema specific part is opaque
        at com.sun.jersey.api.uri.UriBuilderImpl.checkSsp(UriBuilderImpl.java:529) ~[com.sun.jersey.jersey-bundle-1.18.1.jar:1.18.1]
        at com.sun.jersey.api.uri.UriBuilderImpl.path(UriBuilderImpl.java:266) ~[com.sun.jersey.jersey-bundle-1.18.1.jar:1.18.1]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.prepareUrl(ApiClientImpl.java:708) ~[org.graylog2.graylog2-rest-client--1.1.6-1.1.6.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.executeOnAll(ApiClientImpl.java:574) ~[org.graylog2.graylog2-rest-client--1.1.6-1.1.6.jar:na]
        at org.graylog2.restclient.lib.ServerNodesRefreshService.resolveConfiguredNodes(ServerNodesRefreshService.java:92) [org.graylog2.graylog2-rest-client--1.1.6-1.1.6.jar:na]
        at org.graylog2.restclient.lib.ServerNodesRefreshService.access$400(ServerNodesRefreshService.java:42) [org.graylog2.graylog2-rest-client--1.1.6-1.1.6.jar:na]
        at org.graylog2.restclient.lib.ServerNodesRefreshService$1.run(ServerNodesRefreshService.java:126) [org.graylog2.graylog2-rest-client--1.1.6-1.1.6.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_80]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_80]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_80]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

what could be the issue? i tried searching everywhere but no luck. please help.

- HK

**Comment by shiyamk** [comment]
PLease ignore, figured out the issue.

**Comment by Bern9876** [comment]
What was the issue ?

**Comment by joschi** [comment]
@Bern9876 We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Bern9876** [comment]
it was a typo i had in web.conf. just got it to work, Thanks ! 

Bernadette 

----- Original Message -----
