### ISSUE TITLE
Graylog Web Interface 1.1.4 crashing intermittenly

### ISSUE THREAD

**Issue by davidchua** [Graylog2/graylog2-web-interface#1663]
Graylog Web Interface 1.1.4 interfacing with Graylog2 1.1.4

My Graylog Web Interface have been crashing quite frequently (almost every few hours) and in order to get it to work again, I have to start the web interface.

The following is the output from my logs just after the crash.

```
2015-10-27 06:45:04,903 - [ERROR] - from application in New I/O worker #9 


! Internal server error, for (CONNECT) [passport.yandex.ru:443] ->

java.lang.NullPointerException: null
        at play.sockjs.api.SockJSRouter$$anon$1.applyOrElse(SockJSRouter.scala:32) ~[com.github.fdimuccio.play2-sockjs_2.10-0.3.1.jar:0.3.1]
        at play.sockjs.api.SockJSRouter$$anon$1.applyOrElse(SockJSRouter.scala:29) ~[com.github.fdimuccio.play2-sockjs_2.10-0.3.1.jar:0.3.1]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.Router$Include$$anon$17.unapply(Router.scala:103) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_76]
        at Routes$$anonfun$routes$1.applyOrElse(routes_routing.scala:2657) ~[graylog-web-interface.graylog-web-interface-1.1.4.jar:na]
        at Routes$$anonfun$routes$1.applyOrElse(routes_routing.scala:1606) ~[graylog-web-interface.graylog-web-interface-1.1.4.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.Router$Routes$class.handlerFor(Router.scala:454) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at Routes$.handlerFor(routes_routing.scala:18) ~[graylog-web-interface.graylog-web-interface-1.1.4.jar:na]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1$$anonfun$apply$1.apply(GlobalSettings.scala:128) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1$$anonfun$apply$1.apply(GlobalSettings.scala:127) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.flatMap(Option.scala:170) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.flatMap(Option.scala:170) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.GlobalSettings$class.onRouteRequest(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onRouteRequest(JavaGlobalSettingsAdapter.scala:31) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onRouteRequest$2.apply(JavaGlobalSettingsAdapter.scala:31) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onRouteRequest$2.apply(JavaGlobalSettingsAdapter.scala:31) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.getOrElse(Option.scala:120) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaGlobalSettingsAdapter.onRouteRequest(JavaGlobalSettingsAdapter.scala:31) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.GlobalSettings$class.onRequestReceived(GlobalSettings.scala:81) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaGlobalSettingsAdapter.onRequestReceived(JavaGlobalSettingsAdapter.scala:14) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:40) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:39) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.util.Try$.apply(Try.scala:161) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.util.Success.map(Try.scala:206) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.Server$class.sendHandler$1(Server.scala:39) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:72) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:71) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.util.Either$RightProjection.flatMap(Either.scala:523) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.Server$class.getHandlerFor(Server.scala:71) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:39) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.util.Either.fold(Either.scala:98) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:142) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.8.Final.jar:na]
        at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [com.typesafe.netty.netty-http-pipelining-1.1.2.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.9.8.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_76]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_76]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]



2015-10-27 07:57:20,892 - [ERROR] - from application in New I/O worker #8 


! Internal server error, for (CONNECT) [secure.skype.com:443] ->

java.lang.NullPointerException: null
        at play.sockjs.api.SockJSRouter$$anon$1.applyOrElse(SockJSRouter.scala:32) ~[com.github.fdimuccio.play2-sockjs_2.10-0.3.1.jar:0.3.1]
        at play.sockjs.api.SockJSRouter$$anon$1.applyOrElse(SockJSRouter.scala:29) ~[com.github.fdimuccio.play2-sockjs_2.10-0.3.1.jar:0.3.1]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.Router$Include$$anon$17.unapply(Router.scala:103) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_76]
        at Routes$$anonfun$routes$1.applyOrElse(routes_routing.scala:2657) ~[graylog-web-interface.graylog-web-interface-1.1.4.jar:na]
        at Routes$$anonfun$routes$1.applyOrElse(routes_routing.scala:1606) ~[graylog-web-interface.graylog-web-interface-1.1.4.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.Router$Routes$class.handlerFor(Router.scala:454) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at Routes$.handlerFor(routes_routing.scala:18) ~[graylog-web-interface.graylog-web-interface-1.1.4.jar:na]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1$$anonfun$apply$1.apply(GlobalSettings.scala:128) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1$$anonfun$apply$1.apply(GlobalSettings.scala:127) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.flatMap(Option.scala:170) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.flatMap(Option.scala:170) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.GlobalSettings$class.onRouteRequest(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onRouteRequest(JavaGlobalSettingsAdapter.scala:31) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onRouteRequest$2.apply(JavaGlobalSettingsAdapter.scala:31) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onRouteRequest$2.apply(JavaGlobalSettingsAdapter.scala:31) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.getOrElse(Option.scala:120) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaGlobalSettingsAdapter.onRouteRequest(JavaGlobalSettingsAdapter.scala:31) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.GlobalSettings$class.onRequestReceived(GlobalSettings.scala:81) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaGlobalSettingsAdapter.onRequestReceived(JavaGlobalSettingsAdapter.scala:14) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:40) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:39) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.util.Try$.apply(Try.scala:161) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.util.Success.map(Try.scala:206) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.Server$class.sendHandler$1(Server.scala:39) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:72) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:71) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.util.Either$RightProjection.flatMap(Either.scala:523) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.Server$class.getHandlerFor(Server.scala:71) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:39) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.util.Either.fold(Either.scala:98) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:142) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.8.Final.jar:na]
        at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [com.typesafe.netty.netty-http-pipelining-1.1.2.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.9.8.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.9.8.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_76]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_76]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]

2015-10-27 08:13:26,093 - [INFO] - from play in Thread-5 
Shutdown application default Akka system.
```

**Comment by joschi** [comment]
Please upgrade to Graylog 1.2.2 (or at least Graylog 1.1.6).

You can also disable the use of Websockets in the web interface by adding `-Dwebsockets.enabled=false` to its start command.
