### ISSUE TITLE
I can no longer login after upgrade from 2.0.3 to 2.2.1

### ISSUE THREAD

**Issue by stevenmcastano** [Graylog2/graylog2-web-interface#1739]
I get an "Invalid credentials" error message in the web interface and the graylog server current log gives me:

```
2017-04-21_20:27:48.63734 2017-04-21 20:27:48,634 WARN : org.apache.shiro.authc.pam.ModularRealmAuthenticator - Realm [org.graylog2.security.realm.RootAccountRealm@5c076fb2] threw an exception during a multi-realm authentication attempt:
2017-04-21_20:27:48.63796 org.apache.shiro.authc.IncorrectCredentialsException: Submitted credentials for token [org.apache.shiro.authc.UsernamePasswordToken - admin, rememberMe=false] did not match the expected credentials.
2017-04-21_20:27:48.63872       at org.apache.shiro.realm.AuthenticatingRealm.assertCredentialsMatch(AuthenticatingRealm.java:600) ~[graylog.jar:?]
2017-04-21_20:27:48.64219       at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:578) ~[graylog.jar:?]
2017-04-21_20:27:48.64292       at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) [graylog.jar:?]
2017-04-21_20:27:48.64405       at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) [graylog.jar:?]
2017-04-21_20:27:48.64491       at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [graylog.jar:?]
2017-04-21_20:27:48.64609       at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [graylog.jar:?]
2017-04-21_20:27:48.64810       at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) [graylog.jar:?]
2017-04-21_20:27:48.64812       at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) [graylog.jar:?]
2017-04-21_20:27:48.64837       at org.graylog2.rest.resources.system.SessionsResource.newSession(SessionsResource.java:134) [graylog.jar:?]
2017-04-21_20:27:48.64957       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
2017-04-21_20:27:48.65026       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
2017-04-21_20:27:48.65148       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
2017-04-21_20:27:48.65220       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
2017-04-21_20:27:48.65411       at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [graylog.jar:?]
2017-04-21_20:27:48.65524       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [graylog.jar:?]
2017-04-21_20:27:48.65573       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [graylog.jar:?]
2017-04-21_20:27:48.65631       at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [graylog.jar:?]
2017-04-21_20:27:48.65760       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [graylog.jar:?]
2017-04-21_20:27:48.65819       at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [graylog.jar:?]
2017-04-21_20:27:48.65932       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [graylog.jar:?]
2017-04-21_20:27:48.65996       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [graylog.jar:?]
2017-04-21_20:27:48.66504       at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
2017-04-21_20:27:48.66658       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
2017-04-21_20:27:48.66720       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
2017-04-21_20:27:48.67053       at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
2017-04-21_20:27:48.67207       at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
2017-04-21_20:27:48.67276       at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
2017-04-21_20:27:48.67407       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
2017-04-21_20:27:48.67478       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
2017-04-21_20:27:48.67597       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
2017-04-21_20:27:48.67669       at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
2017-04-21_20:27:48.67815       at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
2017-04-21_20:27:48.67881       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
2017-04-21_20:27:48.68317       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
2017-04-21_20:27:48.68641       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
2017-04-21_20:27:48.68773       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2017-04-21_20:27:48.69100 2017-04-21 20:27:48,635 INFO : org.graylog2.rest.resources.system.SessionsResource - Invalid username or password for user "admin"
2017-04-21_20:27:59.80131 2017-04-21 20:27:59,800 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
2017-04-21_20:28:29.80424 2017-04-21 20:28:29,803 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
2017-04-21_20:28:30.15190 2017-04-21 20:28:30,151 WARN : org.graylog2.migrations.V20161130141500_DefaultStreamRecalcIndexRanges - Interrupted or timed out waiting for Elasticsearch cluster, checking again.
2017-04-21_20:28:59.80583 2017-04-21 20:28:59,805 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
2017-04-21_20:29:29.80808 2017-04-21 20:29:29,807 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
2017-04-21_20:29:30.15282 2017-04-21 20:29:30,152 WARN : org.graylog2.migrations.V20161130141500_DefaultStreamRecalcIndexRanges - Interrupted or timed out waiting for Elasticsearch cluster, checking again.
2017-04-21_20:29:59.81022 2017-04-21 20:29:59,809 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
```

Any ideas on what do next??

**Comment by joschi** [comment]
@stevenmcastano Check [`root_password_sha2`](https://github.com/Graylog2/graylog2-server/blob/2.2.3/misc/graylog.conf#L60-L66) in your Graylog configuration file.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
