### ISSUE TITLE
Configure network web-interface

### ISSUE THREAD

**Issue by Mrten** [Graylog2/graylog2-web-interface#623]
I'd like to configure the web interface to listen only on specific ports/interfaces. Have grepped source, cannot even find the '9000' the web interface is listening on so have no idea where to start looking.

**Comment by sathishdsgithub** [comment]
I get the below error while mapping with different port 80 
```

[root@graylog-web-interface-1.0.1]# bin/graylog-web-interface -Dhttp.port=80 -Dhttp.address=192.168.1.10
Play server process ID is 21838
[error] o.g.r.l.ApiClient - API failed due to IO error
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3605) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at org.graylog2.restclient.lib.ApiClientImpl.deserializeJson(ApiClientImpl.java:215) ~[org.graylog2.graylog2-rest-client-1.0.1.jar:na]
[error] o.g.r.l.ApiClient - API failed due to IO error
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3605) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576) ~[com.fasterxml.jackson.core.jackson-databind-2.5.0.jar:2.5.0]
        at org.graylog2.restclient.lib.ApiClientImpl.deserializeJson(ApiClientImpl.java:215) ~[org.graylog2.graylog2-rest-client-1.0.1.jar:na]
[info] play - Application started (Prod)
Oops, cannot start the server.
org.jboss.netty.channel.ChannelException: Failed to bind to: /192.168.1.10:80
        at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
        at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:129)
        at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:126)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer.<init>(NettyServer.scala:126)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:243)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by joschi** [comment]
@sathishdsgithub We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
