### ISSUE TITLE
"Could not parse timestamp of message" error

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#864]
Hi,

I'm using v0.21.0-beta1. 
In rare cases, when searching, i was getting "Oops, an error occured" message.

Server logged following error:

2014-08-06 17:11:34,540 WARN : org.graylog2.indexer.results.ResultMessage - Could not parse timestamp of message null
java.lang.IllegalArgumentException: Invalid format: "1407331093352" is malformed at "3352"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:873)
        at org.graylog2.indexer.results.ResultMessage.setMessage(ResultMessage.java:83)
        at org.graylog2.indexer.results.ResultMessage.parseFromSource(ResultMessage.java:56)
        at org.graylog2.indexer.results.IndexQueryResult.buildResults(IndexQueryResult.java:67)
        at org.graylog2.indexer.results.SearchResult.<init>(SearchResult.java:47)
        at org.graylog2.indexer.searches.Searches.search(Searches.java:167)
        at org.graylog2.rest.resources.search.RelativeSearchResource.searchRelative(RelativeSearchResource.java:94)
        at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:306)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

Further debugging showed, that if timestamp value set to this format "2014-08-06T13:18:13.351Z" - no errors occure. But if timestemp is in unix epoch format - 1407331093352, then web interface displays an error.
REST API request is not showing any errors when timestamp is bogus.

Worth to mention, that i'm running 2 graylog instances (0.12.0 and 0.21.0-beta1) in parallel.
Same message in old graylog has correct timestamp.

I'm open for any additional information.

**Comment by edmundoa** [comment]
This is really old and I haven't heard anything related lately. Please reopen if this is still an issue.

**Comment by mk13d** [comment]
2017-06-21 05:10:26,676 - cwlogs.push.reader - WARNING - 14025 - Thread-10 - Fall back to current time: {'timestamp': 1498021826676, 'start_position': 133562L, 'end_position': 134077L}, reason: timestamp could not be parsed from message.

**Comment by mk13d** [comment]
2017-06-21 05:10:58,764 - cwlogs.push.batch - WARNING - 14025 - Thread-10 - Skip event: {'timestamp': 1498057200000, 'start_position': 244668L, 'end_position': 244735L}, reason: timestamp is more than 2 hours in future.
I am getting these errors on setting timestamp as per answer provided on [stackoverflow](https://stackoverflow.com/questions/40604940/cloudwatch-logs-acting-weird). Please help.

**Comment by joschi** [comment]
@mk13d 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by mk13d** [comment]
my bad , i mistakenly posted aws cloudwatch issue here.
