### ISSUE TITLE
Uncaught error from thread [play-akka.actor.default-dispatcher-79]

### ISSUE THREAD

**Issue by Mowee** [Graylog2/graylog2-web-interface#917]
The web interface just crashed with the following log message after I updated yesterday to the newest version:

Uncaught error from thread [play-akka.actor.default-dispatcher-79] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
Uncaught error from thread [play-akka.actor.default-dispatcher-81] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:713)
        at scala.concurrent.forkjoin.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1672)
        at scala.concurrent.forkjoin.ForkJoinPool.signalWork(ForkJoinPool.java:1966)
        at scala.concurrent.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2037)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Uncaught error from thread [play-akka.actor.default-dispatcher-70] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]

[ERROR] [10/01/2014 11:31:28.186] [play-akka.actor.default-dispatcher-79] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-79] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:713)
        at scala.concurrent.forkjoin.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1672)
        at scala.concurrent.forkjoin.ForkJoinPool.signalWork(ForkJoinPool.java:1966)
        at scala.concurrent.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2037)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ESC[31merrorESC[0m] a.a.ActorSystemImpl - Uncaught error from thread [play-akka.actor.default-dispatcher-81] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[na:1.8.0]
        at java.lang.Thread.start(Thread.java:713) ~[na:1.8.0]
        at scala.concurrent.forkjoin.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1672) ~[org.scala-lang.scala-library-2.10.3.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.deregisterWorker(ForkJoinPool.java:1795) ~[org.scala-lang.scala-library-2.10.3.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:117) ~[org.scala-lang.scala-library-2.10.3.jar:na]
ESC[60G[ESC[0;31mFEHLGESCHLAGENESC[0;39m]

**Comment by Mowee** [comment]
Okay, time for a new status update. I tried again to update from 0.20.6 to 0.90.3
This time my update was successfull. So far I have only tried the update in my test enviroment but I guess since the last time the bug might have been solved. I will try soon to update my productive enviroment.

**Comment by joschi** [comment]
Thanks for the feedback!

I'm closing this issue. Please feel free to add comments if anything new comes up.

**Comment by kalyan220** [comment]
I am using play 2.2.6 with java 1.6 and mongodb. I am facing the same issue what I have to do?
